.github/CODEOWNERS
README.md

Just thought we should reference our other sdk at the top of this readme.

Updated readme to reference the commerce sdk

---

babel.config.js
babel.config.rollup.js
package.json
src/static/clientConfig.test.ts
src/static/clientConfig.ts
src/static/commonParameters.ts
src/static/templateUrl.ts
src/test/crossFetchNode.test.ts
templates/client.ts.hbs
templates/index.ts.hbs
templates/operations.ts.hbs
yarn.lock

Added `transformRequest` option to client config. The function accepts `(data, headers)` and can return any valid request body. The default value is a function that converts plain objects to JSON and sets `Content-Type`, but does not modify the body or headers for any other type. This design is a simplified version of the same option in [axios](https://github.com/axios/axios/blob/b7e954eba3911874575ed241ec2ec38ff8af21bb/lib/defaults.js#L31-L55).
Also:
* Changed `ClientConfig` so that instances of the class have a more rigid structure than the initialization options.
* Got rid of `unknown` types for known types, because that's silly.

Add option to transform request body

---

package.json
yarn.lock

resolves #46
ts-node is used in yarn scripts and should be included in the devDeps

Add ts-node to dev deps

---

.depcheckrc.yml
.eslintrc.json
babel.config.js
package.json
scripts/generate.ts
scripts/templateHelpers.test.ts
scripts/templateHelpers.ts
scripts/updateApis.ts
scripts/utils.test.ts
scripts/utils.ts
src/static/clientConfig.test.ts
src/static/clientConfig.ts
src/static/helpers.ts
src/static/templateUrl.ts
src/test/crossFetchNode.test.ts
src/test/parameters.test.ts
templates/client.ts.hbs
tsconfig.json
yarn.lock

Because of an issue that came up in #63, I wanted to enable [`@typescript-eslint/no-floating-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md). Turns out that took a bit of work. Only code change of substance is in the template helpers.

Type check all TypeScript files and lint most of them, too.

---

src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

As a developer using the isomorphic SDK, I would like the loginRegisteredUserB2C method to not request redirect_uri when running server-side so that my code does not fail if there is not a valid server running on redirect_uri.
AC:
Request is made with manual redirect
Errors are handled in loginRegisteredUserB2C() and the other helpers

 loginRegisteredUserB2C method to not request redirect_uri

---

package.json
src/static/clientConfig.ts
src/static/helpers/index.ts
templates/index.ts.hbs

Hey team, as mentioned in https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/issues/93, the type declarations in this lib are not exported. I'm hoping that we could solve the issue in a minimal / non-breaking way, to unblock the pwa kit team's current React hook work.
After some investigation, I realize the root issue that stops us from exporting the types is the source API RAML specifications contains duplicate type declarations and rollup won't build the lib with the typescript errors.
Create specific types namespaces for each API and export them as `${API}Types`, e.g. `ShopperBasketsTypes`

Export namespaced type declarations

---

package.json

The CI is failing on main branch because the exceeded package size limit. (For some reason it didn't complaint on my branch. I'm guessing the dependencies versions are not locked so the result of each `npm install` gives different dependencies and in turn result in different build?)
This PR bumps up the size to 350kb to have some room.
(I don't quite understand why we need a limit for the whole package. It makes sense to have the limit for JS but I don't think it matters for the rest of the files like type declarations, READMEs etc. 🤷 Shall we remove this test?)

Bump the package size limit to 350kb

---

src/environment/App/App.spec.jsx
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

Small PR that fixes the `logout` function and updates the `authorize` function to use the `ResponseError` class for error handling.

W-11358406: Fix logout function in SLAS helpers

---

src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

Hey team,
I believe there is a bug with the SLAS helpers, specifically the ones that deals with redirect callbacks: `authorize` and `loginRegisteredUserB2C`.
Currently these two helpers will throw an error if the response status is not 303. However, on the browser environment, we always follow the redirect and by following the redirect, the response status will not be 303, but the response from the actual callback endpoint, which is likely a 200 or something. Screenshot below shows that the callback 200 causes the helpers to throw.
Problematic code:
```js
const response = await slasClientCopy.authenticateCustomer(options, true);
// when the redirect is followed on the browser, status will not be 303
// and the if statement will always evaluate to true and throws error
if (response.status …
```

Fix SLAS callback error handling

---

src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

Hi team,
With the recent SLAS release on Sept. 13, SLAS now supports client-id per site rather than client-id per instance. As a result of this change, the calls to log in a user must now include the `channel_id` parameter (which corresponds to the siteId).  
This PR updates the SLAS helper to include `channel_id` when we are calling SLAS endpoints.

Add channel_id to SLAS getAccessToken calls

---

.eslintrc.json
LICENSE.txt
package.json
scripts/updateApis.ts
yarn.lock

1. Load env vars from `.env`. That's done when using `raml-toolkit` directly, but the update APIs script here bypasses that for whatever reason.
2. Copyright year.

Pre-release housekeeping

---

src/static/helpers/types.ts

For `ShopperBaskets<{shortCode: string; organizationId: string}>['getBasket']`, the type is displayed as:
```ts
(method) ShopperBaskets<{ shortCode: string; organizationId: string; }>.getBasket(options?: ({
parameters?: (Omit<{
organizationId: string;
basketId: string;
siteId: string;
locale?: string | undefined;
}, "organizationId" | "shortCode"> & Partial<{
organizationId: string;
basketId: string;
siteId: string;
locale?: string | undefined;
}>) | undefined;
headers?: {
...;
} | undefined;
} & Required<...>) | undefined): Promise<...> (+1 overload)
```
With this change, it's significantly easier to read:
```ts
(method) ShopperBaskets<{ shortCode: string; organizationId: string; }>.getBasket(options?: {
parameters: {
siteId: string;
locale?: string | undefined;
basketId: string; …
```

Add prettify helper to make types more readable.

---

src/static/templateUrl.ts

The cycle is `src/lib/shopperLogin.ts` -> `src/static/templateUrl.ts` -> `src/static/helpers/index.ts` -> `src/static/helpers/slasHelper.ts` -> `src/lib/shopperLogin.ts` 🔁. Changing the import from `helpers/index` to `helpers/types` breaks the cycle.

Fix circular reference.

---

CHANGELOG.md
docs/modules/helpers.html
docs/modules/version.html
package.json
src/static/helpers/environment.ts

- The 'To is not a function' [issue](https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/issues/122) is fixed.

Release v1.10.1

---

.github/workflows/test.yml
README.md
src/test/parameters.test.ts
templates/operations.ts.hbs

This PR adds support for custom query parameters as SCAPI now supports SCAPI hooks: https://developer.salesforce.com/docs/commerce/commerce-api/references/about-commerce-api/about.html#08302023
Query params that begin with `c_` are considered custom query parameters and are passed onto the underlying SCAPI call. Any other query params that aren't a part of the SCAPI endpoint spec will be filtered out and not passed.
This PR also adds node 18 & 20 to the CI
Testing this PR takes a bit of set up:
1. `git clone git@github.com:SalesforceCommerceCloud/commerce-sdk-isomorphic.git`
2. `git checkout ju/support-custom-params`
3. `yarn install`
4. modify `templates/operations.ts.hbs` to add a `console.log()` to check query params:
```javascript
// operations.ts.hbs
...
console.log('URL', …
```

Feat: Add support for custom query parameters @W-13974911@

---

README.md
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

This PR adds support for SLAS [private](https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-private-client.html) client without making a breaking change.
How to test 
1. `git clone git@github.com:SalesforceCommerceCloud/commerce-sdk-isomorphic.git`
2. `git checkout support-slas-client`
3. yarn install
4. npm run renderTemplates && yarn build:lib
5. Create a node project in a separate directory
```
mkdir testSlasPrivateClient
cd testSlasPrivateClient
npm init -y
touch index.js
```
6. modify package.json in testSlasPrivateClient directory to point commerce-sdk-isomorphic to local directory in dependencies section and add "type": "module":
```
"type": "module",
"dependencies": {
"commerce-sdk-isomorphic": "<insert_path_to_local_commerce-sdk-isomorphic>"
}
```
7. npm …

@W-14758586: Support slas client

---

CHANGELOG.md
README.md
src/static/config.ts
src/static/helpers/customApi.test.ts
src/static/helpers/customApi.ts
src/static/helpers/environment.ts
src/static/helpers/fetchHelper.test.ts
src/static/helpers/fetchHelper.ts
src/static/helpers/index.ts
templates/client.ts.hbs
templates/operations.ts.hbs

This PR adds support for custom APIs by exposing a helper function called `callCustomEndpoint` that allows users to call their custom API following common SDK patterns. This PR also pulls out some of the reused logic in `operations.ts.hbs` for fetching data and puts into a helper function called `doFetch`.
Some features of the `callCustomEndpoint` helper:
1. Defaults `apiVersion` to `v1` if not provided
2. Defaults `content-type` header to `application/json` if not provided 
Below is a sample script I used for testing the `callCustomEndpoint` helper function. Reach out to me for instructions on how to run this with the proper credentials.
```javascript
import pkg from 'commerce-sdk-isomorphic';
const { helpers } = pkg;
// replace client credentials
const CLIENT_ID = "clientId";
const …
```

Feat: support custom APIs @W-15111169@

---

CHANGELOG.md
package.json
src/static/helpers/slasHelper.ts
yarn.lock

**Problem**
When Google crawler calls[ createCodeVerifier()](https://github.com/SalesforceCommerceCloud/pwa-kit/blob/37c932ec02d83fe7961ed1b9cb8717eea9952434/packages/template-retail-react-app/app/commerce-api/pkce.js#L22) to create the code verifier we use for the PKCE authentication flow, the result from nanoid() is the same in two different runs.  This causes the same generated code_challenge to be used twice thus Google crawler gets the error stating that the PKCE code_challenge must be unique error.
The root of this issue is the fact that Googlebot’s implementation of random() is deterministic, meaning that it won’t produce unique random values from one string of runs to the next.
The result is that Google crawler indexes the error page instead of the proper page.
**Solution**
Add …

@W-15248536@ - [v3] Google Search Console fix createCodeVerifier

---

package.json
scripts/updateApis.ts
scripts/utils.test.ts
scripts/utils.ts
yarn.lock

The PR removes the usages of the `production` flag by deprecating the `updateApis` command and replacing it with `downloadLatestApis` which pulls the most up to date RAML from Anypoint Exchange.
Related PR: https://github.com/SalesforceCommerceCloud/raml-toolkit/pull/224

@W-15675290@ Remove production flag

---

package.json
scripts/utils.ts
src/test/parameters.test.ts
templates/client.ts.hbs
templates/operations.ts.hbs
templates/paramKeys.ts.hbs

This PR exports the parameter keys for each API method, so that a client like `commerce-sdk-react` will be able to rely on them (and no longer hardcoding those param keys).
For an example on how to consume the exported parameter keys, please see https://github.com/SalesforceCommerceCloud/pwa-kit/pull/1812
Note: this PR is for the parameter _keys_ (not its Typescript types). So we're exporting the list/array.
Previous PR: #157 
In this case, I worked with 2 separate repos: this commerce-sdk-isomorphic (exports the parameter keys) and the pwa-kit (to consume those keys). 
So first of all, let's build the commerce-sdk-isomorphic to get its minified output:
1. `yarn install`
2. `yarn run renderTemplates`
3. `yarn run build:lib`
4. If you need more details: …

Export parameter keys (@W-15676813@)

---

CHANGELOG.md
README.md
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

Starting 7/31/2024, SLAS will start requiring the `channel_id` as a required argument when retrieving an access token with `grant_type: 'client_credentials` for security purposes. This PR updates the `loginGuestUserPrivate` SLAS helper function to require `channel_id`.

Update SLAS helper to require channel_id

---

CHANGELOG.md
package.json
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

This PR adds a new optional parameter `dnt` to SLAS helpers: `loginGuestUserPrivate`, `loginGuestUser` and `loginRegisteredUserB2C`

Add support for SLAS DNT (do not track) parameter

---

package.json
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

In https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/pull/167, `dnt` parameter was added to the SLAS helper but I missed the `refreshAccessToken` helper. This PR fixe it.

Add dnt parameter to SLAS refresh token helper

---

src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts

There was a bug when the `dnt` flag is set to `false`, it will be omitted. This isn't what we want. This PR is to fix this issue.
```js
...(parameters.dnt && {dnt: parameters.dnt.toString()}),
```
```js
...(parameters.dnt !== undefined && {dnt: parameters.dnt.toString()}),
```

[Bug] Fix dnt flag

---

README.md

Add section in the docs for how to handle errors using the SDK.

add docs for error handling

---

CHANGELOG.md
package.json
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts
src/static/helpers/types.ts

This PR allows custom parameters to be passed into `/authorize` endpoint via the `loginGuestUser` and `authorizeIDP` helpers  and `/login` via `loginRegisteredUsers` helper. 
- Customer headers are not allowed and will be ignored via SLAS
Some Note on the authorize endpoint
- The /authorize endpoint does not call SCAPI / OCAPI customers/auth where the hooks take place.
- The /authorize endpoint is used for "Social" or 3rd party logins (okta, Auth0, etc.). SLAS will call out to the given Identity Provider (IDP) to have the user log in.
- For /authorize endpoint the "c_" parameters are passed to the 3rd party IDP and no ECOM hooks are involved.
- /login will have authentication hooks. See [here](https://developer.salesforce.com/docs/commerce/commerce-api/guide/hook-method-details.html)
How …

W-18089100 Allow custom params in helpers

---

CHANGELOG.md
README.md
package.json
scripts/generate-oas.test.ts
src/environment/App/App.jsx
src/static/helpers/fetchHelper.ts
src/static/helpers/slasHelper.test.ts
src/static/helpers/slasHelper.ts
src/static/helpers/types.ts
src/static/templateUrl.test.ts
src/static/templateUrl.ts
templatesOas/apis.mustache
templatesOas/index.mustache

This PR adds a number of refactors:
- SLAS helpers take in 1 options object instead of multiple positional arguments
- Path parameters are encoded by default
- Form parameters have been refactored into a reusable type
- All endpoints accept `c_` custom properties for request body
- API version as client config property has been removed

Feat: Refactor Isomorphic SDK (@W-18709921@)

---

templates/index.ts.hbs
templatesOas/index.mustache

The corresponding ticket is to smoke test `commerce-sdk-isomorphic` by using the PWA Kit and implementing it in the `commerce-sdk-react`. 
To test the OAS isomorphic SDK in the PWA Kit:
1. `git checkout ju/smoke-test-oas-sdk`
2. `yarn install && yarn run renderTemplates && yarn run build:lib`
3. In a separate terminal, navigate to your PWA Kit local repository
4. `git checkout ju/consume-oas-sdk` in PWA Kit: https://github.com/SalesforceCommerceCloud/pwa-kit/pull/2879
5. `npm ci` in PWA Kit
8. Take the generated `lib` directory from `commerce-sdk-isomorphic` and replace it with the one in `commerce-sdk-react`: `pwa-kit/packages/commerce-sdk-react/node_modules/commerce-sdk-isomorphic/lib`
9. `cd packages/commerce-sdk-react` in PWA Kit
10. `npm run build` in commerce-sdk-react
11. `cd …

Fix: Smoke Test SDK(@W-17701726@)

---

CHANGELOG.md
README.md
jest.config.js
package.json
src/static/helpers/environment.ts
src/static/helpers/fetchHelper.test.ts
src/static/helpers/fetchHelper.ts
src/test/setupTests.ts

With the latest major version release, we dropped official support for older node versions and only support node versions 20 & 22. With these versions, node exposes a native fetch function which means we can replace our `node-fetch` polyfill.  This helps resolve an issue with one of our other projects that uses ESM and runs into the following error due to us using `require('node-fetch')` in `environment.ts`:
```
ReferenceError: require is not defined
```
1. The `doFetch` function in `src/static/helpers/fetchHelper.ts` that is used by all endpoints will be calling the node/browser fetch instead of the one defined in `src/static/helpers/environment.ts`
- We unfortunately can't remove the `fetch` function and other unused variables in `environment.ts` as we've already exposed them and …

Fix: require is not defined node-fetch (@W-19399622@)
